"""仓储层抽象接口。用 Python ABC 定义，隔离 YAML 实现细节。"""

from abc import ABC, abstractmethod
from datetime import datetime


class AbstractExperimentRepository(ABC):
    @abstractmethod
    def next_id(self) -> str: ...
    @abstractmethod
    def save(self, experiment: dict) -> str: ...
    @abstractmethod
    def load(self, exp_id: str) -> dict | None: ...
    @abstractmethod
    def update(self, exp_id: str, experiment: dict) -> bool: ...
    @abstractmethod
    def delete(self, exp_id: str) -> bool: ...
    @abstractmethod
    def list_all(self) -> list[dict]: ...
    @abstractmethod
    def list_all_full(self) -> list[dict]: ...
    @abstractmethod
    def summarize_all(self, exp_ids: list[str] | None = None) -> str: ...
    @abstractmethod
    def count(self) -> int: ...


class AbstractAnalysisRepository(ABC):
    @abstractmethod
    def next_id(self) -> str: ...
    @abstractmethod
    def save(self, analysis: dict) -> str: ...
    @abstractmethod
    def load(self, aid: str) -> dict | None: ...
    @abstractmethod
    def list_all(self) -> list[dict]: ...
    @abstractmethod
    def delete(self, aid: str) -> bool: ...


class AbstractThreadRepository(ABC):
    @abstractmethod
    def next_id(self) -> str: ...
    @abstractmethod
    def create(self, thread_type: str, messages: list[dict]) -> dict: ...
    @abstractmethod
    def save(self, thread_data: dict) -> None: ...
    @abstractmethod
    def load(self, thread_id: str) -> dict | None: ...
    @abstractmethod
    def get_index(self) -> dict: ...
    @abstractmethod
    def update_index(self, thread_data: dict) -> None: ...
    @abstractmethod
    def get_active_thread(self) -> dict | None: ...
    @abstractmethod
    def set_active_thread(self, thread_id: str | None) -> None: ...
    @abstractmethod
    def list_recent(self, n: int = 5) -> list[dict]: ...
    @abstractmethod
    def build_global_summary(self, exp_repo: AbstractExperimentRepository,
                              update_log_repo: "AbstractUpdateLogRepository") -> str: ...
    @abstractmethod
    def get_global_context(self) -> str: ...
    @abstractmethod
    def update_global_context(self, compressed_text: str,
                              uncompressed_thread_ids: list[str] | None = None,
                              recently_modified_exps: list[str] | None = None) -> None: ...
    @abstractmethod
    def save_current_state(self, agent_state: dict) -> None: ...
    @abstractmethod
    def load_current_state(self) -> dict | None: ...
    @abstractmethod
    def save_child_state(self, thread_id: str, agent_state: dict) -> None: ...
    @abstractmethod
    def load_child_state(self, thread_id: str) -> dict | None: ...
    @abstractmethod
    def get_user_profile(self) -> dict: ...
    @abstractmethod
    def update_user_profile(self, exp_data: dict) -> None: ...
    @abstractmethod
    def recalc_tag_counts(self, exp_repo: AbstractExperimentRepository) -> None: ...
    @abstractmethod
    def delete_child_state(self, thread_id: str) -> None: ...
    @abstractmethod
    def get_l0_generated_at(self) -> datetime | None: ...


class AbstractFavoritesRepository(ABC):
    @abstractmethod
    def is_pinned(self, exp_id: str) -> bool: ...
    @abstractmethod
    def toggle_pin(self, exp_id: str) -> dict: ...
    @abstractmethod
    def toggle_favorite(self, exp_id: str, collection: str = "默认收藏夹") -> dict: ...
    @abstractmethod
    def get_pinned(self) -> list[str]: ...
    @abstractmethod
    def get_collections(self) -> dict: ...
    @abstractmethod
    def create_collection(self, name: str) -> dict: ...
    @abstractmethod
    def delete_collection(self, name: str) -> dict: ...


class AbstractUpdateLogRepository(ABC):
    @abstractmethod
    def append(self, exp_id: str, source: str, changes: list[dict],
               context: dict | None = None, thread_id: str | None = None) -> str: ...
    @abstractmethod
    def list_recent(self, exp_id: str, limit: int = 5) -> list[dict]: ...
    @abstractmethod
    def list_all(self, exp_id: str) -> list[dict]: ...
    @abstractmethod
    def get_entry(self, exp_id: str, entry_id: str) -> dict | None: ...
